# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6ec8bd5c6e2d1e86e6c29ec5c6c5e1c720ead1b080894ca7312eb729d6c510fb8d99b4a52cb43a31e4090ea2370a65f5d3727f42b3c3354fd5d4a73f007bb179

test:
  secret_key_base: 1e946fd86e43d728f4e5c0d9fe02c05c04f8bf3f56a954077ee5e192187d81033c43cc0e309338e372cb0c27e0a9fa7377b9bf7b9eea86fa748aca909ee34698

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
